language: python

python:
  - "3.7"
  - "3.8"
  - "3.8-dev"
  - "nightly"

install:
  - pip install -U pip setuptools
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install

script:
  - make test
  - make lint

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  allow_failures:
    - python: "3.8-dev"
    - python: "nightly"
