language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -U pip setuptools
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
script:
  - make test
  - make lint
